### ISSUE TITLE
Check reupload issue - duplicate error (delete files)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#418] opened 2023-09-11 08:24 UTC
Original post: [natalia.vanegas@unillanos.edu.co](mailto:natalia.vanegas@unillanos.edu.co)

**Description**
Project https://arbimon.rfcx.org/project/proyecto-mara-on/audiodata/recordings
Related ticket 
- https://github.com/rfcx/arbimon/issues/1299
- https://github.com/rfcx/engineering-support/issues/382

We fixed the timestamps and deleted the files in core so the user should be able to reupload corrupted files. The result from user after the fix is that the reupload showed error as duplicate

![Image](https://user-images.githubusercontent.com/87486094/266955289-13ac7709-6c1c-4308-8ce5-059555a414d2.png)

Additional problem: Some of the recordings are showing white spectrogram https://arbimon.rfcx.org/project/proyecto-mara-on/visualizer/rec/114768015

![Image](https://user-images.githubusercontent.com/87486094/266956042-5783d0e5-413b-4577-8b0c-c5deba8d97f6.png)

![Image](https://user-images.githubusercontent.com/87486094/266956074-4fee628c-dda2-41e3-bad2-2a7ad63b5fba.png)

**Example of recordings in the sites**
https://drive.google.com/file/d/13Vq8vSEoPOS04DiNnAnqWuNzhvtGRHjf/view?ts=64e68c21

**Comment by rassokhin-s** [comment] 2023-09-11 19:23
I checked the data for file `20230518_024500.WAV`. The problem is that checksum for this file differs from the checksum for the data saved in the database
This file: `d0d622b6003b4ffc138786a71fd166fe5eed93f3`
In db: `cc404f63e47a164b19015171dce0f1fac6c3cf47`

There is no other file in this stream with checksum `d0d622b6003b4ffc138786a71fd166fe5eed93f3`.

Do you know how was it deployed originally - with the app or web uploader?

**Comment by koonchaya** [comment] 2023-09-12 09:22
Below, I am providing the name of the site containing the recordings that are experiencing this issue:
L01BPS58 (o9oml4e0awt9)
2023/03/03 12 20230302_202000.WAV 20230303_143500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS70 (plixlmbdfkzc)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 133 20230308_200500.WAV 20230309_185500.WAV

L01MPS75 (xwkaefmsql5t)
2023/03/06 228 20230306_010000.WAV 20230306_195500.WAV
2023/03/07 228 20230307_010000.WAV 20230307_195500.WAV
2023/03/08 228 20230308_010000.WAV 20230308_195500.WAV

L02BPS56 (m05h6cxp9acv)
2023/03/05 41 20230305_153500.WAV 20230305_185500.WAV
2023/03/06 288 20230305_190000.WAV 20230306_185500.WAV
2023/03/07 288 20230306_190000.WAV 20230307_185500.WAV
2023/03/08 288 20230307_190000.WAV 20230308_185500.WAV
2023/03/09 288 20230308_190000.WAV 20230309_185500.WAV

L01BPS69 (n0tlkzbbf6wl)
2023/03/02 87 20230302_114500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS77 (2435te8xtwwe)
2023/03/02 45 20230302_151500.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01SPS80 (6gp3zaezyrxq)
2023/03/03 33 20230303_161500.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01MPS79 (ohhvqodwr52c)
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

L01BPS57 (l15nmvxfqtyd)
2023/03/02 34 20230302_161048.WAV 20230302_185500.WAV
2023/03/03 276 20230302_200000.WAV 20230303_185500.WAV
2023/03/04 276 20230303_200000.WAV 20230304_185500.WAV
2023/03/05 276 20230304_200000.WAV 20230305_185500.WAV
2023/03/06 276 20230305_200000.WAV 20230306_185500.WAV
2023/03/07 276 20230306_200000.WAV 20230307_185500.WAV
2023/03/08 276 20230307_200000.WAV 20230308_185500.WAV
2023/03/09 276 20230308_200000.WAV 20230309_185500.WAV

**Comment by koonchaya** [comment] 2023-09-13 02:25
Delete files for user to be able to upload again

**Comment by rassokhin-s** [comment] 2023-09-13 14:07
> Delete files for user to be able to upload again

@koonchaya will Zhenya work on this? Is anything needed from me still? If no, please reassign the task to Zhenya.

**Closed** 2023-09-19 13:18 UTC
